### ISSUE TITLE
Students should be seeing a nicer message if no evaluations for them

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#105]

**Comment by altermattw** [comment]
Were you thinking of a message that would display if a student is currently not enrolled in any classes (i.e., if  If {{ student.sections.count() }} is zero)?  Or were you thinking of a message that would display after a student has completed all the evaluations for the courses they are enrolled in?

**Comment by skiadas** [comment]
Basically if the list they would get is empty, right now they see nothing on the page, just an empty table. They should instead be seeing some sort of message.
