### ISSUE TITLE
Find appropriate way to reenable javascripts

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#106]
Many edit forms need the typeaheadCollection.js file. It's not ideal to load it specially for each, better to load it centrally. See also comment on https://github.com/skiadas/HanoverEvals/commit/2fb57fcf5e18850d3c63172c13ea5a0f0bf743ce

**Comment by skiadas** [comment]
@altermattw Let me know your thoughts on this when you get a chance.

**Comment by altermattw** [comment]
Use class instead of id to place progress bar.
