### ISSUE TITLE
Tags and Layouts

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#109]
@altermattw I'm thinking we don't need both. Here's how things are set up right now:

- A layout has a name and contains a list of 0 or more questions in an order.
- A tag has a name and may or may not be associated with a layout.
- Departments can be associated with a layout.
- Courses and sections can be associated with both one or more tags and also a single layout.
- Questions from non-tag sources always appear earlier in the evaluation form.
- Questions from tag sources appear grouped within their tag (as they have to belong to the layout associated with that tag) but tag order is somewhat arbitrary.

I feel in this setup we don't gain much by having the two identifications of layout vs tag. I'm thinking a simpler design can work:

- Tags have a name, an optional prompt and 0 or more questions in a specific order (like layout currently does).
- Departments/courses/sections can all be associated with one or more tags.
- When forming the evaluation, the department/course/section hierarchy is preserved, but if multiple tags are associated with the same level then their relative order is somewhat arbitrary.
- There are no "layouts".

So this way we would have:

- A "base" tag with the standard questions, and associated with the "academic affairs" department
- "W1" etc tags associated with "course"s
- "Online" tag associated with sections
- Possibly "lab" tag associated with lab sections

I feel it will serve our needs, and it will be a simpler design.

**Comment by altermattw** [comment]
Interesting idea.  I like it.  It might be a good idea to consider how to add non-question elements to sets of questions, such as section headings (for instructions for blocks of questions, for example).  It might also be a good idea to consider how to manage the order of questions when tag priority is equal. Perhaps “layout” (as a new class) could be used as a way to manage the look and feel of a particular evaluation?

—Bill

On Jul 5, 2016, at 5:32 PM, Haris Skiadas <notifications@github.com<mailto:notifications@github.com>> wrote:


@altermattw<https://github.com/altermattw> I'm thinking we don't need both. Here's how things are set up right now:

  *   A layout has a name and contains a list of 0 or more questions in an order.
  *   A tag has a name and may or may not be associated with a layout.
  *   Departments can be associated with a layout.
  *   Courses and sections can be associated with both one or more tags and also a single layout.
  *   Questions from non-tag sources always appear earlier in the evaluation form.
  *   Questions from tag sources appear grouped within their tag (as they have to belong to the layout associated with that tag) but tag order is somewhat arbitrary.

I feel in this setup we don't gain much by having the two identifications of layout vs tag. I'm thinking a simpler design can work:

  *   Tags have a name, an optional prompt and 0 or more questions in a specific order (like layout currently does).
  *   Departments/courses/sections can all be associated with one or more tags.
  *   When forming the evaluation, the department/course/section hierarchy is preserved, but if multiple tags are associated with the same level then their relative order is somewhat arbitrary.
  *   There are no "layouts".

So this way we would have:

  *   A "base" tag with the standard questions, and associated with the "academic affairs" department
  *   "W1" etc tags associated with "course"s
  *   "Online" tag associated with sections
  *   Possibly "lab" tag associated with lab sections

I feel it will serve our needs, and it will be a simpler design.

**Comment by skiadas** [comment]
I think we can store tag order as a separate variable in the table, using a custom type. I'll give that a go when I try the transition from layouts to tags. So a course object for example, in addition to a "tags" relationship that links it to a number of tags, will also contain a "tagOrder" entry which will be a serialized array of the tag ids in the desired order.

**Comment by skiadas** [comment]
Closing in favor of #111
