### ISSUE TITLE
Make authentication error messages more prominent

### ISSUE THREAD

**Issue by altermattw** [skiadas/HanoverEvals#126]
Most common messsage will be logout due to inactivity.  Enclosing them inside a <div class="alert alert-warning">. Trying this in src/AppBundle/Controller/Admin/SecurityController.php line 22.

**Comment by skiadas** [comment]
You'll probably want to work with views/security/login.html.twig

**Comment by altermattw** [comment]
Excellent suggestion.  That works much better.
