### ISSUE TITLE
Most tables need sorting/filtering functionality

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#130]
As the number of sections increases, we'll need ways to sort and filter the various listings or search for a particular row by typing some words. I imagine these would mostly be Javascript additions. We need to set up some common infrastructure probably.

At the very least I'm thinking:
- [x] All instructor list
- [ ] All student list
- [x] Department list
- [x] All section list and instructor section list
- [x] Course list

**Comment by skiadas** [comment]
@altermattw Looks like we already had an issue about this.

**Comment by altermattw** [comment]
The "all student" list currently can't be filtered because all the columns contain unique information.  If we added "year" to the table, that could be filtered.
