### ISSUE TITLE
Improve look and feel of question view/edit

### ISSUE THREAD

**Issue by altermattw** [skiadas/HanoverEvals#136]
- [ ] For choices, display these as a table with columns "number value," "text value," and a "remove" action button.
- [ ] Add helper text for "Per Instructor" and "Answer Required"

**Comment by skiadas** [comment]
We'll likely have to create the form more manually for this, but doable.

**Comment by altermattw** [comment]
Consider arranging bottom buttons (Cancel, Clone, Delete, Submit) horizontally, with different colors, each inside a <div col-md-3> and add class "btn-block" to justify width.

**Comment by altermattw** [comment]
I'm working on a generic function to print some identified subset of form elements as a table.
