### ISSUE TITLE
Add Question button throwing error

### ISSUE THREAD

**Issue by altermattw** [skiadas/HanoverEvals#141]
On admin/question, pushing the Add Question button results in:
`Neither the property "clone" nor one of the methods "clone()", "getclone()"/"isclone()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView" in admin/question/edit.html.twig at line 15`
Line 15 of admin/question/edit.html is:  `{{ form_widget(form.clone) }}`

**Comment by altermattw** [comment]
This was originally issue #24, and was closed with commit 6b53951.

**Comment by altermattw** [comment]
Commenting out line 15 above just leads to a new error:  the same message about "Neither the property..." but this time applying to the property "delete".  
If you go to an existing question and click the "Clone Question" button, it clones it just fine.  So, the problem may not be the cloning process itself but rather something to do with a new, empty question.

**Comment by skiadas** [comment]
I believe the clone and delete buttons are only conditionally added to the page for non-new questions, as they make no sense for new questions that haven't been created yet. Are we manually creating that page now? If so we need to only conditionally add those buttons, or use `form_rest`

**Comment by altermattw** [comment]
I think you're right.  My analysis below indicates that clone and delete functions are only added if $question_id is not null, and it seems to be null when builder gets to those.  

In admin/question/list.html.twig:
`<a class="btn btn-primary" href="{{ path('admin_question_new') }}">Add a new Question</a>`
Under routing.yml, there is:
```
admin_question_new:
    path: /admin/question/new
    defaults:
        _controller: AppBundle:Admin/Question:edit
        isNew: true
```
And under Admin/QuestionController:
```
public function editAction($question_id = null, $isNew, Request $request)
    {
        $qm = $this->get('model.question');
        $question = $isNew ? $qm->makeText() :
                             $qm->find($question_id);
```
And under AppBundle/Model/QuestionModel.php:
```
    public function makeText($prompt = '', $perInstructor = false)
    {
        return $this->make($prompt, Question::TextType, $perInstructor);
    }
```
where make is defined as:
```
    public function make($prompt, $type, $perInstructor = false)
    {
        $question = new Question();
        $question->setPrompt($prompt)->setType($type)
            ->setPerInstructor($perInstructor);

        $this->em->persist($question);

        return $question;
    }
```
So, for new questions, QuestionController `$question = $isNew ? $qm->makeText() :` should return a new Question() with an empty prompt, type set to TextType, and perInstructor set to false.     Looking ahead, one concern is that editAction's $question_id parameter sets it to null.  After defining $question, QuestionController's editAction would then proceed to:
```
        $hasAnswers = $qm->hasAnswers($question_id);
```
where hasAnswers is defined as:
```
    public function hasAnswers($question_id)
    {
        $answerRepo = $this->em->getRepository('AppBundle:Answer');

        return !is_null($answerRepo->findOneByQuestion($question_id));
    }
```
and so should return FALSE.  Later, QuestionController proceeds with:
```
        $builder = $this->createFormBuilder($question)
                ->add('edit', ButtonType::class,
                    array('label' => 'Unlock Question for Editing'))
...
        if (!is_null($question_id)) {
            $builder->add('delete', SubmitType::class, array(
                'label' => 'Delete Question',
                'attr' => array('formnovalidate' => 'formnovalidate'),
            ))
            ->add('clone', SubmitType::class, array(
                'label' => 'Clone Question',
                'attr' => array('formnovalidate' => 'formnovalidate'),
            ));
        }
```
So, delete and clone are never added to new questions, but the Edit form is expecting them when those widgets are rendered.

**Comment by skiadas** [comment]
But only because we hand-wrote the edit form at some recent time? If we let the system do the form itself, without rendering each widget ourselves via our own twig form, it probably works fine. Our twig form should not try to add things that are not there, that's why we are seeing the errors I think.

**Comment by altermattw** [comment]
I'll work on adding an {% if %} clause around these lines in edit.html.twig:
```
<div class="row button-wrapper">
            <div class="col-sm-4">
               {{ form_widget(form.clone) }}
            </div>
            <div class="col-sm-4">
               {{ form_row(form.edit) }}
            </div>
         </div>
```

**Comment by altermattw** [comment]
That's right; it's because I was customizing the way it displayed using the twig form fields.  One alternative is to add all the style (including moving things around) after the document renders, using jQuery.  I'll work on adding {% if %} tags around clone and delete.

**Comment by altermattw** [comment]
In addition to hiding clone and delete, would it be okay if we also hid the form.edit button, the one that unlocks the form?  By default, new questions are open (unlocked).

**Comment by skiadas** [comment]
I suppose we could, yes.
