### ISSUE TITLE
Make form to import .csv file of new courses

### ISSUE THREAD

**Issue by altermattw** [skiadas/HanoverEvals#152]

**Comment by skiadas** [comment]
@altermattw I created most of the workhorse for this (though the cross-listing is still not quite working). The pages could probably use some formatting. They are admin/update and admin/updateResults

**Comment by altermattw** [comment]
Hi, Haris,

I tried the import using the data that Dawn sent, but it said 0 imported.  Does it only work on the server?

—Bill
________________________
Bill Altermatt, Ph.D.
Department of Psychology
Hanover College
altermattw@hanover.edu<mailto:altermattw@hanover.edu>



On Aug 26, 2016, at 7:18 PM, Haris Skiadas <notifications@github.com<mailto:notifications@github.com>> wrote:


@altermattw<https://github.com/altermattw> I created most of the workhorse for this (though the cross-listing is still not quite working). The pages could probably use some formatting. They are admin/update and admin/updateResults

**Comment by skiadas** [comment]
You need to migrate the database first, cause I added the departments as a migration. That might have been it.

Also make sure to use the “ansi” file that dawn sent. Did she send it to you too or just to me?

**Comment by altermattw** [comment]
I did the migration, but I’m afraid it still didn’t work.  Maybe I don’t have the right file.  Could you email me the correct version?

—Bill
________________________
Bill Altermatt, Ph.D.
Department of Psychology
Hanover College
altermattw@hanover.edu<mailto:altermattw@hanover.edu>



On Aug 28, 2016, at 12:29 PM, Haris Skiadas <notifications@github.com<mailto:notifications@github.com>> wrote:

You need to migrate the database first, cause I added the departments as a migration. That might have been it.

Also make sure to use the “ansi” file that dawn sent. Did she send it to you too or just to me?

**Comment by skiadas** [comment]
I'm gonna close this. I think it is quite old at this point and superseded by the new stuff I am working on.
