### ISSUE TITLE
Create "locked" state for sections

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#168]
- [x] Sections now have a new "locked" boolean property.
- [x] Sections enter that the locked state when the first evaluation is submitted. 
- [x] Any tags associated with the course/department at the time get stored as section tags. 
- [x] A locked section's tags cannot be edited.
- [x] When a section becomes locked, all tags from its course or department must be copied to it.
- [x] When looking up a section's tags, if the section is locked then don't look up the course chain.
- [x] Make a separate migration for this.
- [ ] Show message for locked sections

**Comment by skiadas** [comment]
@altermattw You'll need to do a "php bin/console doctrine:migrations:migrate" to get the database back in order once you pull this commit in. 

Also there's some work for you to do on this one if you can, in app/Resources/views/admin/section/edit.html.twig
There is a warning message there that needs to be inserted when the section is locked, I've created a placeholder. Close this issue when you add it.

**Comment by skiadas** [comment]
@altermattw Were you able to migrate your local setup smoothly?

**Comment by altermattw** [comment]
I ran the migration without errors but haven't checked out the site yet. Is there an easy way to test the locked feature?  Maybe if I filled out a student's eval for a section, then checked the instructor's view?  I'll try to give that a try tonight or tomorrow.

Bill

Sent from my iPhone

On Jun 16, 2017, at 12:55 PM, Haris Skiadas <notifications@github.com<mailto:notifications@github.com>> wrote:


@altermattw<https://github.com/altermattw> Were you able to migrate your local setup smoothly?

**Comment by skiadas** [comment]
Yes if you create an eval it should lock that section. You would see the message when you go to "edit" the section.

You could also lock a section directly in the database, via mysqlworkbench.

**Comment by skiadas** [comment]
Hm actually I don't think I've made it so that a section is locked when an evaluation is submitted. So the only way to turn a section to locked right now is manually in the database.

**Comment by skiadas** [comment]
Actually I am wrong again. The locking is set up when a new evaluation is created in the make method of EvaluationModel. So yes, completing an evaluation should do it.

**Comment by altermattw** [comment]
Tested this and it performs as expected.  If you log in as an admin and go to “Sections,” you can select a section and add new tags to it.  If you then submit an evaluation for that section as a student in that section and then go back to the tag editing screen for that section, you get a warning message at the top saying that it’s locked to editing.  If you try to edit it, when you click submit, no changes are made and you are taken to the screen showing the roster of all sections.

—Bill
________________________
Bill Altermatt, Ph.D.
Department of Psychology
Hanover College
altermattw@hanover.edu<mailto:altermattw@hanover.edu>



On Jun 16, 2017, at 10:30 PM, Haris Skiadas <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually I am wrong again. The locking is set up when a new evaluation is created in the make method of EvaluationModel. So yes, completing an evaluation should do it.
