### ISSUE TITLE
Make direct links to pdf versions of evaluations

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#170]
In the section view for an instructor, currently there are buttons that take you to the evaluation results pages in html form, and those pages then have links to pdf versions. It would be nice if we had those pdf links in the section view page also. This would speed up the work that admins have to go through to get a person's files downloaded for FEC.

**Comment by altermattw** [comment]
Closed by commit 4b8831f2d1d9f5421a93389c4875e1cb5a47cace.
