### ISSUE TITLE
admin/tag/new causes internal server error

### ISSUE THREAD

**Issue by altermattw** [skiadas/HanoverEvals#171]
Creating a new Tag returns an error.

**Comment by altermattw** [comment]
/admin/tag/edit/[number] also returns an Internal Server Error.  This is reached by going to the Tag menu and clicking on the Edit button to the right of a tag label.

**Comment by skiadas** [comment]
@altermattw So, I just tried this and it seemed to work fine. Do you still have trouble with it? Is your database up-to-date?

**Comment by altermattw** [comment]
It looks like it’s working on our local version, but the evals.hanover.edu<http://evals.hanover.edu> site version of it does not work, so we can’t add the new questions to tags yet.  I’m guessing you haven’t pushed the recent changes to evals.hanover?

On Jul 30, 2017, at 9:03 PM, Haris Skiadas <notifications@github.com<mailto:notifications@github.com>> wrote:


@altermattw<https://github.com/altermattw> So, I just tried this and it seemed to work fine. Do you still have trouble with it? Is your database up-to-date?

**Comment by skiadas** [comment]
Hm I see what you mean, I'm going to have to check it out. I was pretty certain that I had updated this part.

**Comment by skiadas** [comment]
Ok it should work out now. Btw you shouldn't be creating a new tag if you want to update the questions on an existing tag. You should simply edit that tag. On save it will clone the tag to a new version and keep the old one around for those sections that have already used it in their evaluations.

**Comment by altermattw** [comment]
Looks good.
