### ISSUE TITLE
Query not working

### ISSUE THREAD

**Issue by altermattw** [skiadas/HanoverEvals#180]
I've tried 4 queries of different types but none seem to work.  Got the following message:
```
Attempted to load class "IfElse" from namespace "DoctrineExtensions\Query\Mysql".
Did you forget a "use" statement for another namespace?
```
Here is the log right before the error:
`
DEBUG - SELECT h0_.question_id AS question_id_0, h0_.prompt AS prompt_1, h0_.type AS type_2, h0_.per_instructor AS per_instructor_3, h0_.answer_required AS answer_required_4, h1_.id AS id_5, h1_.num_value AS num_value_6, h1_.text_value AS text_value_7, h1_.question AS question_8 FROM hanev_questions h0_ INNER JOIN hanev_choices h1_ ON h0_.question_id = h1_.question WHERE h0_.type = 'Multiple Choice, Single Answer' OR h0_.type = 'Multiple Choice, Multiple Answers' 
`

**Comment by altermattw** [comment]
This is on the QuerySystem branch.

**Comment by skiadas** [comment]
So yeah, this patch introduces some new bundles, they are vendor bundles and not part of the commits. I think you'll need to do a "composer update" for it to install those bundles.

**Comment by skiadas** [comment]
If you run into out-of-memory issues, you may have to try something like:
```
php -d memory_limit=-1 /usr/local/bin/composer update
```

**Comment by altermattw** [comment]
That fixed it.  Thanks!

**Comment by altermattw** [comment]
Thanks!  I did run out of memory, so this was helpful.  The queries are running now and I closed the issue.

Here’s something weird, though:  I ran a query of my PSY 111 course and it correctly reported all the questions that students answered, but it also included the questions for online courses, the new basic layout questions, AL, HS, PP, RP, SM, and I think everything else.  I checked the Section table and PSY 111 is listed as only "Basic Layout" and “HS”.  Any idea why the query is pulling in all the questions?

—Bill
________________________
Bill Altermatt, Ph.D.
Department of Psychology
Hanover College
altermattw@hanover.edu<mailto:altermattw@hanover.edu>



On Aug 16, 2017, at 6:45 PM, Haris Skiadas <notifications@github.com<mailto:notifications@github.com>> wrote:


If you run into out-of-memory issues, you may have to try something like:

php -d memory_limit=-1 /usr/local/bin/composer update

**Comment by skiadas** [comment]
The query isn't really meant for specific courses per se, so it is not set up to try to detect which questions to include. I should probably make it not include any questions without answers though.
