### ISSUE TITLE
Old Tags appearing in Query Edit

### ISSUE THREAD

**Issue by altermattw** [skiadas/HanoverEvals#186]
This is a similar problem to commit 896f59a under the QuerySystem branch, where the Tags were repeating in the dropdown field.  This is occurring in the Question Filter section of query/edit.  Note how in the image below, HFA marks the beginning of the repeat:

<img width="229" alt="screen shot 2017-09-19 at 9 31 10 am" src="https://user-images.githubusercontent.com/3475519/30594836-70be963c-9d1d-11e7-998a-86727cc7b09f.png">

**Comment by skiadas** [comment]
Two parts to this:

- Limiting the list of visible tags.
- Making sure that a query for LA actually uses all the LA tags.
