### ISSUE TITLE
Decide on web server infrastructure

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#2]
PHP? Node? Python? Ruby? Something else?

**Comment by skiadas** [comment]
I have been looking on using [CodeIgniter](https://www.codeigniter.com/) for the server infrastructure, it seems to be nice with what I've seen so far. It's a PHP framework, and PHP is currently the only scripting language we have running on our servers. We could of course also talk to John about supporting some other language.

We'll have to decide on front-end stuff too.

**Comment by altermattw** [comment]
I would be very happy with PHP, as it's the only server-side language I've used.  I read about CodeIgniter and it sounds like it is easy to learn and the coding is fairly explicit PHP, which I think I would like.  I'd be up for learning something new.  What are the advantages of using CodeIgniter as opposed to just writing all the PHP independently?


For the front end, my preference would be Bootstrap for handling layout.  I've used it a lot and am pretty comfortable with it.  What do you think?


____________________________
Bill Altermatt, Ph.D.
Department of Psychology
Hanover College


________________________________

**Comment by skiadas** [comment]
One of the main advantages of something like CodeIgniter is that it offers a more high-level access to the database, for starters. It has a QueryBuilder that you can use to create the queries and not worry about sanitizing the inputs (avoiding things like sql injections, see https://xkcd.com/327/ ). Other than that it offers some routing functionality so we can write urls like ".../instructor/skiadas/2015/fall" or things of this sort. And of course implements a Model-View-Controller separation.

Bootstrap sounds great for the UI, HTML/CSS stuff. And maybe d3.js for graphics, if we don't end up using our own library, which is still at its infancy.

**Comment by skiadas** [comment]
Using Symfony now.
