### ISSUE TITLE
defining form_start, etc.

### ISSUE THREAD

**Issue by altermattw** [skiadas/HanoverEvals#36]
For app/Resources/views/student/eval.html.twig, there are 3 functions:  form_start(form), form_widget(form), and form_end(form).  Where are these defined?   Are they related to evalFormAction in StudentController?

**Comment by skiadas** [comment]
These come from Symfony's form infrastructure:

http://symfony.com/doc/current/book/forms.html#rendering-a-form-in-a-template and http://symfony.com/doc/current/cookbook/form/form_customization.html

We'll need to possibly change these for more customized behavior. On the other hand a lot might happen automatically if we switch to the bootstrap "theme". The above links should be a good start point for that.
