### ISSUE TITLE
get('model') -> enrollment

### ISSUE THREAD

**Issue by altermattw** [skiadas/HanoverEvals#37]
src/AppBundle/Controller/StudentController.php evalFormAction function generates the evaluation form. What is meant by this:
get(‘model’) -> enrollment

**Comment by skiadas** [comment]
get('model') returns an instance of the ModelManager, in /src/AppBundle/Model/ModelManager.php

It contains as properties the various other files in the Model folder. These files are the way to access the actual underlying "Entities", which are meant to be simple objects that the database ORM handles. The Model folder contains our code for accessing these entities. So the ->enrollment part returns an instance of /src/appBundle/Model/EnrollmentModel.php which contains methods related to managing information related to the Enrollment entity.

In general when I need a new method to access something from the database, I add it to one of the Model files, the one that seems most appropriate.

**Comment by skiadas** [comment]
Feel free to close these issues when you no longer need them.
