### ISSUE TITLE
Improve error page reporting

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#52]
See http://symfony.com/doc/current/cookbook/controller/error_pages.html

**Comment by skiadas** [comment]
@altermattw You may want to customize the pages further at some point. Close the issue if/when they look ok. The templates are in `app/Resources/TwigBundle/views`. You can look at read some more about it at http://symfony.com/doc/current/cookbook/controller/error_pages.html

To test them at production, point the browser at the paths `/_error/404`, `/_error/403`, `/_error/500`

**Comment by altermattw** [comment]
I looked at them a bit, but wasn't quite sure what the goal is. They currently report 2-3 types of errors, but those seemed pretty generic (e.g., file not found). Is there a way to provide more helpful or specific information, or do those three files just need some more bootstrap styling?

Bill

Sent from my iPhone

On Jun 30, 2016, at 3:28 PM, Haris Skiadas <notifications@github.com<mailto:notifications@github.com>> wrote:


@altermattw<https://github.com/altermattw> Did you get a chance to look at this?

-

**Comment by skiadas** [comment]
Yeah I was just thinking of some bootstrapification.
