### ISSUE TITLE
Add contact/help information

### ISSUE THREAD

**Issue by altermattw** [skiadas/HanoverEvals#54]
The name and email address of the person to contact if the user needs help should be stored as a variable somewhere that could be modified by admin.

**Comment by altermattw** [comment]
@skiadas, what would be the best way to do this?  In SummerCourseData.php, there is a line that assigns Elsa to admin:
```
$admin = $this->getModel()->admin;
$elsa = $admin->make('conboy', 'Conboy', 'Elsa');
```
and this refers to the "make" function in AdminModel.php:
```
public function make($login, $last, $first)
    {
        $admin = new Admin();
        $admin->setLogin($login)
            ->setLast($last)
            ->setFirst($first);

        $this->em->persist($admin);

        return $admin;
    }
```
However, there is no "get" function in AdminModel, so I'm not sure how to extract the name and email address of the current administrator so that we could list it in a "Help" link.  Could we use the "find" or "findAll" functions of the base Model?

**Comment by skiadas** [comment]
Exactly, each model inherits the find and findAll methods from the base Model class. So you can get a list of all admins by doing:

```
$this->get('model')->admin->findAll();
```

That will be a list of all admins.

Or we could just hard-code it for now.

**Comment by altermattw** [comment]
Hard-coded into footer with commit 6773566.  However, footer is not visible on phone-sized screens, so need another way to include contact information as well.
