### ISSUE TITLE
Use a date-picker for terms

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#60]
Currently terms are implemented via the "choice" option in DateType (http://symfony.com/doc/current/reference/forms/types/date.html) 

It would be nice to use some sort of bootstrap datepicker at some point.

**Comment by altermattw** [comment]
Symfony's documentation for the DateType field (http://symfony.com/doc/current/reference/forms/types/date.html#rendering-a-single-html5-textbox) suggests using eternicode's bootstrap-datepicker:
https://eternicode.github.io/bootstrap-datepicker/

CDN:
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.1/css/bootstrap-datepicker.min.css
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.1/js/bootstrap-datepicker.min.js

Usage:
$('#sandbox-container div').datepicker({
    todayBtn: "linked",
    todayHighlight: true
});
