### ISSUE TITLE
Decrease font size and other changes for the printed generated reports

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#79]

**Comment by altermattw** [comment]
Need to add "--print-media-type" as an option to wkhtmltopdf so that it relies on the @media print css instead of the default @media screen.

**Comment by skiadas** [comment]
That part's already done in config.yml

**Comment by skiadas** [comment]
I added a skeleton structure. Not sure quite yet how to change the font size. Also would like to encourage page breaks before each evaluation and discourage them in the middle. Need to find out the best way to do that.

**Comment by altermattw** [comment]
We've got parallel print css files. I've got the body font changing fine, but for some reason wkhtmltopdf is not picking up on the @media print instructions, despite the config setting.  I'll start working on getting Symfony to process LESS files, which will help with changing how the table classes are displayed.

**Comment by skiadas** [comment]
Just overwrite mine, I just put it as a stump here. Will need to figure out why it's not being picked up.

Do we really need to mess with the less files?

**Comment by altermattw** [comment]
It's not absolutely necessary.  If we don't, we'll have to manually add all the css styling associated with Bootstrap's "table-condensed" class for the @media print setting.  I'll start with that.  If we have to do much more over-riding of the original Bootstrap, it might be handy to have less enabled.  Just in case it's useful for later, here's a site on how to add less:  http://isometriks.com/using-less-with-symfony2

**Comment by skiadas** [comment]
So looking at it further, the print setting in config.yml does work, as it does indeed trigger bootstrap's print css settings. For some reason it's our print media settings that it's not reading.

**Comment by altermattw** [comment]
May be a problem with wkhtmltopdf reading relative links to the local CSS files.  When I removed the CDN link to Bootstrap and replaced it with a local copy of bootstrap.min.css, the webpage rendered just fine, but when I clicked on the "Get it as PDF!" button, I got this error message:
```
The exit status code '1' says something went wrong:
stderr: "Loading pages (1/6)
[> ] 0%
[======> ] 10%
[===========> ] 19%
Warning: Failed to load file:///css/51c56cc_part_1_navbar_2.css (ignore)
Warning: Failed to load file:///css/51c56cc_part_1_printing_3.css (ignore)
```

**Comment by altermattw** [comment]
Several websites have complained about wkhtmltopdf not reading relative links to CSS files (or images). E.g., http://stackoverflow.com/questions/16627310/wkhtmltopdf-not-loading-local-css-and-images  
Maybe we could get symfony to generate an absolute path, e.g., http://symfony.com/doc/current/reference/twig_reference.html#absolute-url
?

**Comment by skiadas** [comment]
I wonder if it has to do with running it via the php server, and that it would run fine once we get it deployed.

**Comment by skiadas** [comment]
@altermattw for now let's just add the print media as an explicit style tag, something like the following just as the "head" tag closes:

```
        <style type="text/css">
        @media print {
          body * {
            font-size: 5pt;
          }
        }
        </style>
```

It will then read that just fine. Prevents the browser from cacheing it, but if it's not too large it won't matter.

**Comment by altermattw** [comment]
Close with commit fde21ae
