### ISSUE TITLE
Problem with admin/term page

### ISSUE THREAD

**Issue by altermattw** [skiadas/HanoverEvals#84]
Clicking on "Term" gets me: 
`An exception has been thrown during the rendering of a template ("getTextperiod: This term value should not happen") in admin/term/list.html.twig at line 32.`
The trouble is with that line:
`<td>{{ term.textPeriod }}</td>`
because deleting it permits the page to display.  Here's the getTextperiod function from Entity/Term.php:
```
public function getTextPeriod()
    {
        $sub = $this->getPeriod();
        if (is_null($sub)) {
            return '';
        }
        if (array_key_exists($sub, self::$periods)) {
            return self::$periods[$sub];
        }
        throw new \LogicException('getTextperiod: This term value should not happen');
    }

```

**Comment by skiadas** [comment]
Yeah that's a consequence of the fact that we don't have the summer data on github. I've made the changes to fix this on my end, but you're probably working with an outdated summer fixtures file. I'll send you the new version and after you test it you can close this.

**Comment by altermattw** [comment]
Works great now.
