### ISSUE TITLE
Layouts should have "prompts"

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#87]
The prompt would show up above the list of questions for a topic.

Alternatively we can let a "question" actually be a "prompt", not expecting answer. Not sure which one is easier to code. The second is certainly more flexible in terms of what it allows.

**Comment by altermattw** [comment]
Were you thinking of these elements acting as section headings, introducing a set of questions?

Sent from my iPhone

On Jun 29, 2016, at 3:27 PM, Haris Skiadas <notifications@github.com<mailto:notifications@github.com>> wrote:


The prompt would show up above the list of questions for a topic.

Alternatively we can let a "question" actually be a "prompt", not expecting answer. Not sure which one is easier to code. The second is certainly more flexible in terms of what it allows.

-

**Comment by skiadas** [comment]
Exactly. But right now we don't have the infrastructure for that: The questions get collected together into one long list, and there's no record of which layout they came from.

**Comment by skiadas** [comment]
Closing this as it should be part of the work on #109
