### ISSUE TITLE
wkhtmltopdf not working on the server

### ISSUE THREAD

**Issue by skiadas** [skiadas/HanoverEvals#88]
Trying to troubleshoot it with John.

For now the pdf functionality isn't working.

**Comment by skiadas** [comment]
Fixed. We should update the docs

**Comment by altermattw** [comment]
Hurray!

Sent from my iPhone

On Jun 30, 2016, at 3:57 PM, Haris Skiadas <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed. We should update the docs

-
